version: '3.7'

services:
  code:
    container_name: code
    build: ./source
    ports:
      - "80:80"
    volumes:
      - ./source/code:/var/www/html:bind
    restart: always
    depends_on:
      - mariadb
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
  
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    volumes:
      - ./dbdata:/var/lib/mysql:bind